sudo: required
services:
  - docker
before_install:
  - docker build -t ol/rect-test -f ./client/Dockerfile.dev .

script: 
  - docker run -e CI=true ol/rect-test npm test -- --coverage
    
after_success: 
  - docker build -t aniknaemmmm/multi-client ./client
  - docker build -t aniknaemmmm/multi-nginx ./nginx
  - docker build -t aniknaemmmm/multi-server ./server
  - docker build -t aniknaemmmm/multi-worker ./worker
  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    
  - docker push aniknaemmmm/multi-client
  - docker push aniknaemmmm/multi-nginx
  - docker push aniknaemmmm/multi-server
  - docker push aniknaemmmm/multi-worker
