sudo: required
services:
  - docker
before_install:
  - docker build -t ol/rect-test -f ./client/Dockerfile.dev

script: 
  - docker run -e CI=true ol/rect-test npm test -- --coverage
    
after_success: 
  - docker build -t ol/multi-client ./client
  - docker build -t ol/multi-nginx ./nginx
  - docker build -t ol/multi-server ./server
  - docker build -t ol/multi-worker ./worker